### PR TITLE
Create automatic generator for the constants.dart file  - fixes #11

### LINKED ISSUE #11: Tool used to generate lib\src\constants\constants.dart should be included.
I am assuming that there is a dart program (tool) that is used to generate the `constants.dart` file.
It would make sense to include this in a `tool\` or `generator\` subdirectory so that users have the option of regenerating this file themselves when the GoogleFonts package is updated to include new fonts (as it recently was updated to 4.0.3).

The tool should also be updated to write a header to the `constants.dart` file to specify the version of the GoogleFonts package it was generated for and the command used to generate it (ie. something like "Excecute `dart run tools\updateConstants.dart` from the root of the package to regenerate this file"). 

I would assume you are generating this file from information returned by the google fonts rest api as described [here](https://developers.google.com/fonts/docs/developer_api).  
This tool would require the user to create their own key as described [here](https://support.google.com/googleapi/answer/6158862?hl=en&ref_topic=7013279).
The page at [https://developers.google.com/fonts/docs/developer_api](https://developers.google.com/fonts/docs/developer_api) does include an 'execute' button which automatically grabs the latest json file.  Optionally we could allow the tool to read this json from a local file so that generating an API key was not required.

If you have not already created such a tool I would be happy to create one, otherwise I would be more than happy to clean up any existing code that exists to generate the `constants.dart` file and submit a PR (if you could provide the existing source).

What I am imagining doing is taking the font list from the google_fonts version specified in the pubspec.yaml file and then looking up each included font in the json file from the google fonts api and retrieving the required data.. and then writing out the new constants.dart file.

### PR DESCRIPTION
**Pull request by timmaffett**
This PR adds a new automatic generator program for the `constants.dart` file.   This fixes the #11 issue I submitted.
This can be run to automate the creation of `constants.dart` any time there is a change to the google_fonts package version (or if updated google fonts api information is desired).
The output of this program attempts to closely match the format of the existing constants.dart file, and can be diff'ed against the currrent versions to examine it's contents/changes made.

There are changes to the existing constants.dart file to move the fontweight map to it's own file.  This is required so that the generator program (`generator/update_constants.dart`) can include the previous `constants.dart` file to determine all changes (additions and removals) that are being made and report this.  

All of the below details should essentially also be found in the `generator/readme.md` file.

There is a new program (`example\display_googlefonts_fontlist.dart`) which can be run to capture a list of the fonts included in the root pubspec.yaml file.  This is required because the generator is a dart program and it cannot directly include the flutter google_fonts package, so this intermediary program must be used to gather this info.   This font list is then copied from this program and saved into a file within the generator directory to later be passed to `update_constants.dart`.
(This is not (strictly speaking) *required*, but if it is the google_fonts package font list is NOT passed to `update_constants,dart` then there are (potentially many) fonts included in the output `constants.dart` file which the google_package does not include support for.

The generator program will automatically query a google fonts API to retrieve the font info Json (using your own private/secret API key), or this can be gathered manually using the 'EXECUTE' button found at [https://developers.google.com/fonts/docs/developer_api](https://developers.google.com/fonts/docs/developer_api) .  If it is gathered manually it is then saved into as local file within the generator directory.   And example file is present in this PR.  (which was verified to be identical to the once retrieved using my own private API key as of it's generation).

The output of the `update_constants.dart` file is included in the generator directory of this PR.  I did not update the ACTUAL `/lib/src/constants/constants,dart` file so that you can go through the process/run the generator yourself, and see how it all works.  This will list the new and removed fonts and languages, etc.

I used the `--legacylanguages` option when generating the included `generator/constants.dart` file, this preserves the language list from the previous version of `constants.dart`.

The PR contains example files for the google_fonts 4.0.3 version (`googlefonts_4.0.3_fontlist.txt`), the google fonts API json (`api_output_feb_22_23.json`) as well as the output of the tool  (`constants_generated_feb_22_23.dart`).
These are all found within the generator directory.

Complete details can be found in the `generator/readme.md` file, but to run it with the included json/fontlist files listed above

```
cd generator
dart run update_constants.dart -g googlefonts_4.0.3_fontlist.txt -i api_output_feb_22_23.json --legacylanguages
```

and a new `constants.dart` file will be created in the current (`generator`) directory.

### CODE REVIEW

**Comment by whiplashoo** [comment]
Impressive! Thanks for taking the time to implement this!

Indeed, I think that generating the constants.dart file via the google_fonts package should be included, to avoid previously reported issues, with fonts or their variants, weights, etc. missing.

I would intend this generator tool to be used **exclusively by maintainers of this package**, and not from end users that might just depend on it. This means that, when the `google_fonts` package is updated, we should rerun the generator, update the `constants` file, and publish a new version for `flutter_font_picker`.

Some thoughts on this PR:

- I think that the `display_googlefonts_fontslist.dart` extractor, while it works fine, is a bit cumbersome? I can see that in the `google_fonts` package, there is the `[families_supported](https://github.com/material-foundation/flutter-packages/blob/main/packages/google_fonts/generator/families_supported)` file, that lists the fonts list directly. I think it would be better to add an instruction for maintainers to get that directly from there (or fetch it in the `update_constants.dart` file?).
- Seeing some formatting issues in the `update_constants.dart` file, but I will fix them myself when closing the PR.

The rest of the changes look good. Thanks again for your work on this.

**Comment by timmaffett** [comment]
I did not notice that https://github.com/material-foundation/flutter
-packages/blob/main/packages/google_fonts/generator/families_supported existed.  That is DEFINETLY a better way to get that font list!   I am glad I only spend a few minutes making display_googlefonts_fontlist.dart.. lol   
   I will modify the tool to grab that directly and display an error if for some reason the URL does not resolve.
I will update the PR immediately.

**Comment by timmaffett** [comment]
ps. and this is definitely for the maintainers of the package, in practice, but the option is now there for user to update it themselves if the google_fonts package is updated and this package has not yet been. 

* or if they manually update their own google_fonts package - which is often very far behind in getting the new fonts.

For this reason (*) I will leave in the option of using a text file for the source of the google fonts list, but retrieve the list from the URL if it is not provided on the command line.

**Comment by timmaffett** [comment]
OK. I have added the automatic retrieval of the google_fonts font list from [`https://raw.githubusercontent.com/material-foundation/flutter-packages/main/packages/google_fonts/generator/families_supported`](https://raw.githubusercontent.com/material-foundation/flutter-packages/main/packages/google_fonts/generator/families_supported) 
I also added a --verbose flag that has to be added to output the big lists of fonts/etc.  
..and fixed a couple output message bugs.

**Comment by timmaffett** [comment]
.and out of curiosity I was wondering what the formatting issues were, generally, so that I can avoid them in the future.

**Comment by timmaffett** [comment]
I also updated the readme to reflect the change.

I reference optionally using the `example\display_googlefonts_fontlist.dart` program to get a font list (and editing it) - but we can also just entirely remove `example\display_googlefonts_fontlist.dart` as well.  
Your call.

**Comment by whiplashoo** [comment]
Looks good! I just merged this PR.

I think that it's better to remove the `example/display_googlefonts_fontlist.dart` tool, to keep it simpler. If sometime in the future, the `families_supported` file from the google_fonts package is not directly available, we can revert to using it.

I also updated and cleaned up the generator README.

Finally, regarding formatting, I just use [Effective Dart](https://dart.dev/guides/language/effective-dart), which is applied via executing `dart format` (or `dartfmt`) on save, since I use VS Code. Which editor do you use? You can find some info [here](https://docs.flutter.dev/development/tools/formatting).

Thanks again, and I will be looking into the other PR soon.

**Comment by timmaffett** [comment]
I agree about `example/display_googlefonts_fontlist.dart`.

I use VSCode as well (most of the time, sometimes android studio).  We use dart analyze/dart format religiously within the dart-lang repositories.   I neglected to run my pr's here through it, as some authors do not use it.  I should have checked.

**Pull request merged**
